apiVersion: v2
name: swagger-template
version: 0.1.2
description: Bootstrap Swagger UI.
sources:
  - https://github.com/ganiulis/charts
maintainers:
  - name: Gintaras Aniulis
    email: messageme@ganiulis.com
    url: https://github.com/ganiulis
appVersion: "1.0.0"
