apiVersion: v2
name: api-template
version: 0.4.2
description: Bootstrap a generic API. See [changes from the previous version](https://github.com/ganiulis/charts/compare/api-template-0.4.1...api-template-0.4.2).
sources:
  - https://github.com/ganiulis/charts
maintainers:
  - name: Gintaras Aniulis
    email: messageme@ganiulis.com
    url: https://github.com/ganiulis
appVersion: "1.0.0"
