apiVersion: v2
name: api-template
version: 0.2.0
description: A template for bootstrapping a generic API instance
sources:
  - https://github.com/ganiulis/charts
maintainers:
  - name: Gintaras Aniulis
    email: messageme@ganiulis.com
    url: https://github.com/ganiulis
appVersion: "1.0.0"
