namespace: default
environment: test
container:
  name: api
  image: golang
  version: latest
  port: 8080
  replicas: 2
  imagePullSecret: regcred
  envPath: /api # Optional. Requires base64-encoded .env data to be stored in a [CONTAINER_NAME]-dotenv Secret.
host:
  domain: ganiulis.com
  path: /api # Optional. Skips Middleware if removed.
  clusterIssuer: letsencrypt # Optional.
  tlsSecret: letsencrypt # Optional.
