apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.container.name }}
  labels:
    environment: {{ .Values.environment }}
    app: {{ .Values.container.name }} 
    app.kubernetes.io/name: {{ .Values.container.name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: {{ .Values.container.name }}
  ports:
    - port: 5432
  clusterIP: None
