apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    environment: {{ .Values.environment }}
    app: {{ .Values.name }} 
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.container.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.container.imagePullSecret }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.version | default "latest" }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-env
          {{- if .Values.volumes.list }}
          volumeMounts:
          {{- range .Values.volumes.list }}
            - name: {{ $.Values.name }}-{{ .name }}
              mountPath: {{ .containerPath }}{{ .file }}
              {{- if .file }}
              subPath: {{ .file }}
              readOnly: true
              {{- end }}
          {{- end }}
          {{- end }}
      {{- if .Values.volumes.groupId }}
      securityContext:
        fsGroup: {{ .Values.volumes.groupId }}
      {{- end }}
      {{- if .Values.volumes.list }}
      volumes:
      {{- range .Values.volumes.list }}
        - name: {{ $.Values.name }}-{{ .name }}
          {{- if .file }}
          secret:
            secretName: {{ $.Values.name }}-{{ .name }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ $.Values.name }}-{{ .name }}
          {{- end }}
      {{- end }}
      {{- end }}

