apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }} 
  labels:
    environment: {{ .Values.environment }}
    app: {{ .Values.name }} 
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: Helm
  annotations:
    {{- if .Values.host.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.host.clusterIssuer }}
    {{- end }}
    {{- if .Values.host.path }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace }}-{{ .Values.name }}@kubernetescrd
    {{- end }}
spec:
  ingressClassName: traefik
  rules:
    {{- if .Values.host.subdomain }}
    - host: {{ .Values.host.subdomain }}.{{ .Values.host.domain }}
    {{- else }}
    - host: www.{{ .Values.host.domain }}
      http:
        paths:
          - path: {{ .Values.host.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 80
    - host: {{ .Values.host.domain }}
    {{- end }}
      http:
        paths:
          - path: {{ .Values.host.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 80
  {{- if .Values.host.certEmail }}
  tls:
    - secretName: letsencrypt
      hosts:
        {{- if .Values.host.subdomain }}
        - {{- .Values.host.subdomain }}.{{ .Values.host.domain }}
        {{- else }}
        - www.{{ .Values.host.domain }}
        - {{ .Values.host.domain }}
        {{- end }}
  {{- end }}
