{{- range .Values.volumes.list }}
{{- if .hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $.Values.name }}-{{ .name }}
  labels:
    type: local
    environment: {{ $.Values.environment }}
    app: {{ $.Values.name }}
    app.kubernetes.io/name: {{ $.Values.name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .hostPath }}
{{- end }}
{{- end }}
